runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  DATABASE_URL: postgresql://neondb_owner:npg_kz1dqWbQ8fpB@ep-flat-mountain-abr2hj5p-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require

  BETTER_AUTH_SECRET: bBg9PTTCb1vcrfQTjSkiBQ08knSq3gnx

  PORT: 8080

  NODE_ENV: production

  BETTER_AUTH_URL: https://taskflow-sj63g.ondigitalocean.app

  BACKEND_URL: https://cuthub-bd55d.ew.r.appspot.com

  GOOGLE_CLIENT_ID: 55149849690-ifhj260ajlmmiscqrt833o79nei7vcc8.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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

  GITHUB_CLIENT_ID: Ov23liGVrm3DTr4Py1xK
  GITHUB_CLIENT_SECRET: 677cd50c0f34c9b280b831d7cbd7b565c14cbb21

  TWITTER_CLIENT_ID: Y1hrdVhYMlNBNmVTSlBqLWdQUF86MTpjaQ
  TWITTER_CLIENT_SECRET: ZtxuASI6evp63pX3N_bdUwGpOM5syU8rEWECvRcmDyYOYLa0_W

  DISCORD_CLIENT_ID: 1346247846789386343
  DISCORD_CLIENT_SECRET: FMjA-_I5fWREqiWC4Mc4KH-BtU-Uv6XX

  LINKEDIN_CLIENT_ID: 78pi6wom7cag4s
  LINKEDIN_CLIENT_SECRET: "WPL_AP1.hJ5JcAOelYqH9vdp.E6J0iQ=="

  FRONTEND_WEB_URL: https://taskflow-sj63g.ondigitalocean.app

  MAILGUN_API_KEY: bbdc194ee8fd1147a4dd04fbe1f21adf-e298dd8e-f80c3d1f

  RESEND_API_KEY: re_XC9GceNt_A8G5EBh4zW8fseWtkXKuNbLY

  STRIPE_API_KEY: pk_test_51QznVQBGod976ROEbSBurNuM10RIaJ1SzpKEPg5HnqfD7AT66NycaqtVgjmcq6SOCxgOpCts0ic4doVsxv77pAFz005KZOBhkK
  STRIPE_SECRET_KEY: sk_test_51QznVQBGod976ROE24bDJgXkJC8VdD4GlM1gWOwIDXRVi0qEyhF4geTc3KfrXRJrGqpLGvcgDWJ047qGQepkE8fo00Y3eVCtLx
  STRIPE_WEBHOOK_SECRET: whsec_f028aa65894086817e42956008867a28a9202ead833529791d1e56ca8470d7b1

  STRIPE_FREE_MONTHLY_PRICE_ID: price_1R9vTrBGod976ROEq57bo4sU
  STRIPE_FREE_ANNUAL_PRICE_ID: price_1R9vU4BGod976ROEFCBTJiKe

  STRIPE_INDIVIDUAL_MONTHLY_PRICE_ID: price_1QzoFqBGod976ROEt8lcQ8xa
  STRIPE_INDIVIDUAL_ANNUAL_PRICE_ID: price_1QzoFqBGod976ROE4IhEGsnq

  STRIPE_TEAM_MONTHLY_PRICE_ID: price_1QzoGMBGod976ROEWAnqeJPd
  STRIPE_TEAM_ANNUAL_PRICE_ID: price_1QzoGlBGod976ROEeb7gw6nw

  ENCRYPTION_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcGZFajQxSHNVSWZzakVrUTRLNmpEY1hEbVBkQ0dkNC9jNUtueU5BbEVxNE9xRlFiClYzb20raDIyTHVWU096cGVYdzdDQlhHM3A0ejk4MkRMTHowVEVQUlVjM3pGcTNFSGllK3kxaG9VeG9YMTN2NHgKOHJKenBCcGFMdkk2T3p3dXRsUlJPNzl5L1Q0V2tLdlVjdHhGR0lCWXdIenJVTC9sV2hwY2JCUDFtVVVYM0JDMgpwWmZMdDVtZHM2ZVJmOHlPeSt4RzIyZktLKytTa1RibHR0akhndCs4YWZ0b1lrTlN5UWpQajVVd29BTFhpOVoxCmJRUGZmQXl5VTJzWVNLWVc5U0tSL0VuK0VvaEF0Rkl5WnArdTRSU1JMc2U3aGZhYnRwVGV4amRuYkJZZjFuWkQKTkMyNGxNM1YzVFZHRU12aDRwMUhzd2p2Uk9GbzdBL1NuVm1iVlFJREFRQUJBb0lCQUJZNWxVWnBYdjZzTGNUZQpObG41V2RKSzVmY1RTckdmUUIxUkM1TE1PZUxtR0FWNGVrNzloOEhnLzlrSkVybm5CK093WE5FUTJYbWgyeE5oCkorVjBSeHp5dEdyaFQ3STJDYjN5TWlBVnp5bUZvSmdVc0lqaVdMV21aK1M0d1k3VWNTY3ZaTS9kUk4vaEZIR2MKNmUvV1M1VEwvOWNNQkJKRkdVazNsYUJPRGd0UWE5cW42QnZHd0ZsQ0JQQ2xJMlk5U1JwQVVsT0dmdmxDamM1VwpNZS9ITmhuRTBUMW5xUFJmOGtvRlF3MlFjcGwwVDE4OUttV1VIc1QrME1qTk5ZVzBwcWNDd3F5U09JQUxBdjRUCmhzV3Y3T1hRWlNyV1BHbmh1dGVHN01HNDdhS2NnLzgwV084TEt3d0ZWMFR2dFoyeHdWbHVOSUEvRjZNNTRIcVgKeFJQTkYwRUNnWUVBM0oxbmdTeHZwT2w1aGgrNVd2MnFOeldGK0ZTUzNrV09xbWJjNFV4QjByckw3WFFJc1pYSQpHcDRkbEdPbkxSbTZkTzJHYWJleVdFbk9vVnFManpRcDZmM1NYN0lLb293QktXZ0NVZU9vM2pYa00zejlwVTZMCllsRjBjcC9LeEZPUE5jOEM5cENhUno1Mm9rM3dxUkkzUUlqNEdGZzNZc3MzYS9Hb0hHWDl5SFVDZ1lFQXdJN1UKU3d6bUR4Zm5QaWl6aTVadGpNakZTQ2lTOXJvNG9LQXVIWC9ja0NsR0V5d2NmMm1aUVV3akNZSUMrcDRLYWVUTgo5cmR5Y2g3dXN1ajZhcVg0MVVMQW1FV2tkU1BDS2lhb3FVQllLc0QvQkw5aUlqcXVZc0kraHcwTGhTdStId3VuCm5rTUJqZW4zQ011Q2kyelF0YnMrOWtQR2JPeHFTT2xPa1BEUksyRUNnWUJXdEhKQ2ZWRmZrZmNWOUkvbnAveG0KK0YwdnpTVnZ3QXlqQWd4YmE1b1BGU1Vpck5EaDRva2psUEx4Si8xREozSjFsQWlZc2Y2ZzNsa2NaemFrVUk4TQpqSnBLeS9HTUV0UStEc2Vpb1lQejJXQlhzQThNRWdPTDM1R1JueVdVNVhaS1lwSzZqdmhqZWJRc2M4OWEwM0x0CnBTZEVnaDg2YjczWGFjRjFiOHcvSlFLQmdERE9RdXErMnpUcUp4ZHZNNHJtMXQ5L0o5blJSdWE0Ym8vdjZhQmEKZnlvZSsvN3lDRXNYRmR3aUV5TmV5NmlBRkQyZzI3OXo0ZE1oR2ZsSTZlZk1KNVRPTllpaTVqczJsQWtoQVZEYwoyVHdFN041a0w5aGpMVDRrNDdwUlNTRTQ1QmgwV01qWlRQU09YNm5nQXplWm5oRGg0K1NCYXpMQ2ZYSDdpSWxlCk1IWWhBb0dCQUp5YjRuYnVOU2R2YnpUeDl0MytaQ0R0eHBkcC9obGo0bFZabVZZZGFjZDVhT1d1bVA1OHZobzYKd3VYTHdSUnR0R05NWEhYaEhUZU5ZU1dzWkN4VGFuTklWZXdQMGY3aGpZdVRwdm4wZkt2Vlp2c2oxdUxoY0ZBWQpMWkdHUXJ3TEZFRk8ySnZubXFQeW9SOHZvS1BmTXBjRkU0eFYxRDA0TVpmS0VheWs3NkYvCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg

  GEMINI_API_KEY: AIzaSyBO2hrDPCbNUboIgHFARxSmxI3Hu4o5wac

  UPLOADTHING_TOKEN: "eyJhcGlLZXkiOiJza19saXZlX2NjZDc1OTgxODllNjkzM2E5MTVhMTI5NzNmNGFkNWYyNDQ0ZjAwODEyMDNmY2U4MTkxNDNhY2YyOGYyM2VlNzgiLCJhcHBJZCI6Im1nZnBoN3I4eTQiLCJyZWdpb25zIjpbInNlYTEiXX0="

  CLOUDINARY_CLOUD_NAME: dqcbm2dnj
  CLOUDINARY_API_KEY: 439327166917762
  CLOUDINARY_API_SECRET: Ty53W6mIz1Fb37E3OVddJyOCWSQ

  MAX_FILE_SIZE: 41943040

handlers:
  - url: /.*
    script: auto
    secure: always
